services:
  liuzx-ra:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ra
    image: liuzx-ra:${LIUZX_RA_VERSION}
    env_file:
      - .env
    ports:
      - "${RA_PORT:-5443}:4443"
    environment:
      - LANG=zh_CN.UTF-8
      - TZ=Asia/Shanghai
      - JAVA_OPTS=${JAVA_OPTS:--Xms512m -Xmx1024m -Xmn256m}
      - SERVER_PORT=4443
      - SERVICE_ID=liuzx-ra
      - NODE_ID=${NODE_ID:-1}
      - MYSQL_HOST=${MYSQL_HOST:-mysql}
      - MYSQL_PORT=${MYSQL_PORT:-3306}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-lcloud_ra_4}
      - MYSQL_DOMAIN_DATABASE=${MYSQL_DOMAIN_DATABASE:-lcloud_platform_domain_4}
      - MYSQL_USERNAME=${MYSQL_USERNAME:-root}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - JASYPT_SECRET_KEY=${JASYPT_SECRET_KEY}
      - SECURITY_ENABLED=${SECURITY_ENABLED:-false}
      - NACOS_DISCOVERY_ENABLED=${NACOS_DISCOVERY_ENABLED:-false}
      - NACOS_CONFIG_ENABLED=${NACOS_CONFIG_ENABLED:-false}
      - NACOS_ADDRESS=${NACOS_ADDRESS:-nacos:8848}
      - NACOS_NAMESPACE=${NACOS_NAMESPACE:-0dac1a68-2f01-40df-bd26-bf0cb199057a}
      - NACOS_GROUP=${NACOS_GROUP:-LIUZX_GROUP}
      - NACOS_USERNAME=${NACOS_USERNAME:-nacos}
      - NACOS_PASSWORD=${NACOS_PASSWORD:-nacos}
      - SPRING_CLOUD_BOOTSTRAP_ENABLED=false
      - SPRING_CONFIG_LOCATION=file:/app/application.yml
    volumes:
      - ./logs:/tmp
      - ./data:/home/ra/data
      - ./application.yml:/app/application.yml:ro
    restart: unless-stopped
    networks:
      - pki-network

networks:
  pki-network:
    external: true
    name: pki-network
