services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "11111111"
      MYSQL_ROOT_HOST: "%" # 允许 root 从任意主机连接（容器初始化时生效）
      TZ: Asia/Shanghai
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=caching_sha2_password
    volumes:
      - ./data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/
    networks:
      - pki-network

networks:
  pki-network:
    external: true
    name: pki-network
