[ HSM ]
MODE = 0            # 工作模式 0-默认工作模式 204-检测中心检测平台适配模式 仅HSM下有效 默认-0
IP = 211.88.20.90       # 服务器密码机业务IP
PORT = 1815         # 服务器密码机业务端口
POOLSIZE = 32       # TCP连接池大小
CONNTIMEOUT = 3000  # TCP连接超时毫秒
RWTIMEOUT = 5000    # 通信超时毫秒 应根据实际业务性能调整
INTERVALTIME = 600  # TCP连接异常重试秒
MAXSESSION = 1024   # 密码机最大会话句柄数量 默认1024

[SVS]
APPCODE = timeStamp

[ LOG ]
DIR = /tmp/hsm-logs # 日志存储路径 未配置-当前路径
LEVEL = 1       # 日志等级 0-不输出 1-错误输出 2-警告输出 3-信息输出 4-调试输出 未配置-1
SIZE = 0        # 分割日志文件字节 0-不分割 小于1048576(1M)时使用1048576 未配置-0
SPAN = 0        # 日志分割 0-不分割  1-按天分割 2-按月分割 3-按年分割 未配置-0
NAME = sdhsm.log # 日志输出方式 stdout-标准输出 stderr-标准错误输出 其他-输出文件名 未配置-stderr
TRACK = 0       # 调用日志输出 0-不输出 1-输出调用日志 2-增加整型及地址输出 3-增加缓冲区部分输出 4-增加缓冲区全部输出 未配置-0

#[ SSL ] #是否开启SSL,注释掉本行可关闭SSL
#CACERT = ./clientcert/GMCA01.cert.pem					#CA证书路径
#CLIENTCERT = ./clientcert/ShuDunTLSv3Client.cert.pem  	#客户端证书路径
#CLIENTPRIKEY = ./clientcert/ShuDunTLSv3Client.key.pem 	#客户端私钥路径
#MINVERSION = TLS1.1	#TLS协议最低版本要求,不配置该项默认TLS1.1,取值:TLS1.1/TLS1.2/TLS1.3
#MAXVERSION = TLS1.3 #TLS协议最高版本要求,不配置该项默认TLS1.3,取值:TLS1.1/TLS1.2/TLS1.3
#CIPHERSUITES = TLS_SM4_GCM_SM3 #加密套件,国密算法只在TLS1.3中支持,注释掉该配置项则支持所有的算法,取值参考:TLS_SM4_GCM_SM3/TLS_SM4_CCM_SM3/TLS_AES_128_GCM_SHA256/TLS_AES_256_GCM_SHA384
#AUTHENTICATIONTYPE = 1 #认证方式,取值0:单向ssl认证,1:双向ssl认证
